### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Frolikow** [p-tka4enko/ui-kit-project#19]
Заметил у тебя в главном файле верстки макета неправильные классы:
```pug
.main-wrapper

  .main-wrapper__buttons
    .buttons
      .buttons__title-wrapper
        h2.title Standard buttons
      .buttons__container
        .buttons__row
          .buttons__button-wrapper.buttons__button-wrapper_small
            +button({text: "Button", size: "small"})
          .buttons__button-wrapper
```

Здесь у тебя прям много `блоков в блоке`, что противоречит БЭМу. 
Нужно максимально компонентной сделать верстку, вынести все блоки. Заодно главные  [стили](https://github.com/p-tka4enko/ui-kit-project/blob/master/src/pages/ui-kit/ui-kit.styl) разгрузишь.  
и обрати внимание на ` h2.title `

**Comment by p-tka4enko** [comment]
> и обрати внимание на h2.title

А что здесь имелось в виду?)

**Comment by Frolikow** [comment]
> > и обрати внимание на h2.title
> 
> А что здесь имелось в виду?)

Здесь я имел ввиду то, что сейчас это блок .title ) а блоки как выше писал - должны быть реализованы отдельно)
